@{
    RootModule           = 'PoshUI.psm1'
    ModuleVersion        = '4.1.0'
    GUID                 = 'db92996d-fec9-4d71-9fd4-40194906da3b'
    Author               = 'Nick Ferguson'
    CompanyName          = 'Nick Ferguson'
    Copyright            = '(c) Nick Ferguson. All rights reserved.'
    Description          = 'Composable terminal UI components, structured logging, and interactive prompts for PowerShell.'
    PowerShellVersion    = '7.6'
    CompatiblePSEditions = @('Core')
    FunctionsToExport    = @(
        'Get-PoshUIConfiguration'
        'Get-PoshUIRuntime'
        'New-PoshUITheme'
        'Set-PoshUITheme'
        'Set-PoshUILogConfiguration'
        'Get-PoshUILogConfiguration'
        'Write-PoshUILog'
        'Clear-PoshUILog'
        'Format-PoshUIHeader'
        'Show-PoshUIHeader'
        'Format-PoshUISubheader'
        'Show-PoshUISubheader'
        'Format-PoshUIStatus'
        'New-PoshUIProgress'
        'Update-PoshUIProgress'
        'Format-PoshUIProgress'
        'Show-PoshUIProgress'
        'Format-PoshUIBox'
        'Show-PoshUIBox'
        'New-PoshUITable'
        'Set-PoshUITableHeader'
        'Add-PoshUITableRow'
        'Set-PoshUITableAlignment'
        'Format-PoshUITable'
        'Show-PoshUITable'
        'Format-PoshUIHorizontalBarChart'
        'Show-PoshUIHorizontalBarChart'
        'Format-PoshUISparkline'
        'Show-PoshUISparkline'
        'Format-PoshUIGauge'
        'Show-PoshUIGauge'
        'New-PoshUIMenu'
        'Add-PoshUIMenuItem'
        'Format-PoshUIMenu'
        'Show-PoshUIMenu'
        'Invoke-PoshUIMenuAction'
        'Read-PoshUIText'
        'Read-PoshUIPassword'
        'Confirm-PoshUIChoice'
        'Select-PoshUIOption'
        'Select-PoshUIMultipleOption'
        'Read-PoshUINumber'
        'Read-PoshUIFilePath'
        'Read-PoshUIDirectoryPath'
        'Format-PoshUIText'
        'Format-PoshUIPanel'
        'Show-PoshUIPanel'
        'Format-PoshUIStack'
        'Show-PoshUIStack'
        'Format-PoshUIColumn'
        'Show-PoshUIColumn'
        'Format-PoshUIGrid'
        'Show-PoshUIGrid'
        'New-PoshUIDataColumn'
        'Format-PoshUIDataTable'
        'Show-PoshUIDataTable'
        'Format-PoshUITree'
        'Show-PoshUITree'
        'Format-PoshUICodeBlock'
        'Show-PoshUICodeBlock'
        'Format-PoshUIDiff'
        'Show-PoshUIDiff'
        'New-PoshUIStepper'
        'Add-PoshUIStep'
        'Set-PoshUIStep'
        'Format-PoshUIStepper'
        'Show-PoshUIStepper'
        'New-PoshUILiveRegion'
        'Set-PoshUILiveRegionContent'
        'Remove-PoshUILiveRegionContent'
        'Add-PoshUILiveRegionMessage'
        'Format-PoshUILiveRegion'
        'Show-PoshUILiveRegion'
        'Update-PoshUILiveRegion'
        'Close-PoshUILiveRegion'
        'Invoke-PoshUILiveRegion'
        'New-PoshUISelectionItem'
        'Find-PoshUISelectionItem'
        'New-PoshUISearchSelection'
        'Update-PoshUISearchSelection'
        'Format-PoshUISearchSelection'
        'Select-PoshUIItem'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags         = @('terminal', 'ui', 'console', 'logging', 'jsonl', 'cross-platform')
            ProjectUri   = 'https://github.com/NickCrew/PoshUI'
            ReleaseNotes = 'https://github.com/NickCrew/PoshUI/blob/main/CHANGELOG.md'
        }
    }
}
