#Requires -Version 7.6

<#
.SYNOPSIS
    Regenerates the PoshUI command reference

.DESCRIPTION
    Builds docs/reference from the explicit manifest inventory and the
    comment-based help exposed by the imported PoshUI module. Check mode
    generates into an isolated temporary directory and fails when committed
    output is stale.

.PARAMETER ManifestPath
    Path to the PoshUI module manifest.

.PARAMETER OutputRoot
    Directory that receives the generated reference files.

.PARAMETER Check
    Verifies generated output without changing the working tree.

.INPUTS
    None.

.OUTPUTS
    None.

.EXAMPLE
    PS> ./tools/Update-Docs.ps1

    Regenerates docs/reference.

.EXAMPLE
    PS> ./tools/Update-Docs.ps1 -Check

    Fails when the committed reference is stale.

.EXAMPLE
    PS> ./tools/Update-Docs.ps1 -OutputRoot ./generated-reference

    Generates the reference in another directory.
#>
[Diagnostics.CodeAnalysis.SuppressMessageAttribute(
    'PSAvoidUsingWriteHost', '',
    Justification = 'Maintainer-facing status is the script output.')]
[CmdletBinding(SupportsShouldProcess)]
[OutputType([void])]
param(
    [ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })]
    [string]$ManifestPath = (Join-Path $PSScriptRoot '..' 'powershell' 'PoshUI.psd1'),

    [string]$OutputRoot = (Join-Path $PSScriptRoot '..' 'docs' 'reference'),

    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:GeneratedNotice = '<!-- Generated by tools/Update-Docs.ps1. Do not edit manually. -->'
$script:ResolvedManifest = (Resolve-Path -LiteralPath $ManifestPath).Path
$script:Manifest = Import-PowerShellDataFile -LiteralPath $script:ResolvedManifest
$script:Commands = @($script:Manifest.FunctionsToExport)
$script:Module = $null

function Add-PoshUIDocLineInternal {
    param(
        [System.Collections.Generic.List[string]]$Lines,

        [AllowEmptyString()]
        [string]$Text = ''
    )

    $Lines.Add($Text)
}

function ConvertTo-PoshUIDocArrayInternal {
    param([object]$Value)

    if ($null -eq $Value) { return @() }
    if ($Value -is [array]) { return @($Value) }
    @($Value)
}

function Get-PoshUIDocPropertyInternal {
    param(
        [object]$InputObject,
        [Parameter(Mandatory)][string]$Name
    )

    if ($null -eq $InputObject) { return $null }
    $property = $InputObject.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    $property.Value
}

function Get-PoshUIDocHelpTextInternal {
    param([object]$Value)

    $parts = [System.Collections.Generic.List[string]]::new()
    foreach ($item in (ConvertTo-PoshUIDocArrayInternal $Value)) {
        if ($null -eq $item) { continue }
        $text = Get-PoshUIDocPropertyInternal -InputObject $item -Name Text
        if ($null -eq $text) { $text = [string]$item }
        if (-not [string]::IsNullOrWhiteSpace([string]$text)) {
            $parts.Add((([string]$text) -replace "`r`n", "`n").TrimEnd())
        }
    }
    ($parts -join "`n").Trim()
}

function ConvertTo-PoshUIDocCellInternal {
    param([object]$Value)

    if ($null -eq $Value) { return '' }
    $text = (([string]$Value) -replace "`r`n", "`n").Replace('|', '\|')
    ($text -replace "`n", '<br>').Trim()
}

function ConvertTo-PoshUIDocBoolInternal {
    param([object]$Value)

    switch ([string]$Value) {
        'true' { 'Yes' }
        'false' { 'No' }
        default { [string]$Value }
    }
}

function Write-PoshUIDocFileInternal {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][AllowEmptyString()][string[]]$Lines
    )

    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
        [void](New-Item -ItemType Directory -Path $parent -Force)
    }
    $content = (($Lines -join "`n").TrimEnd("`r", "`n")) + "`n"
    [IO.File]::WriteAllText($Path, $content, [Text.UTF8Encoding]::new($false))
}

function Get-PoshUICommandReferenceInternal {
    param([Parameter(Mandatory)][string]$CommandName)

    $command = $script:Module.ExportedCommands[$CommandName]
    if ($null -eq $command) {
        throw "Manifest command was not exported by the imported module: $CommandName"
    }

    $help = Get-Help -Name $command -Full
    $parameters = @(ConvertTo-PoshUIDocArrayInternal (
            Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $help -Name parameters
            ) -Name parameter
        ))
    $examples = @(ConvertTo-PoshUIDocArrayInternal (
            Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $help -Name examples
            ) -Name example
        ))
    $inputs = @(ConvertTo-PoshUIDocArrayInternal (
            Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $help -Name inputTypes
            ) -Name inputType
        ))
    $outputs = @(ConvertTo-PoshUIDocArrayInternal (
            Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $help -Name returnValues
            ) -Name returnValue
        ))
    $notes = @(ConvertTo-PoshUIDocArrayInternal (
            Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $help -Name alertSet
            ) -Name alert
        ))

    $lines = [System.Collections.Generic.List[string]]::new()
    Add-PoshUIDocLineInternal -Lines $lines -Text "## $CommandName"
    Add-PoshUIDocLineInternal -Lines $lines

    $synopsis = [string](Get-PoshUIDocPropertyInternal -InputObject $help -Name Synopsis)
    if (-not [string]::IsNullOrWhiteSpace($synopsis)) {
        Add-PoshUIDocLineInternal -Lines $lines -Text $synopsis.Trim()
        Add-PoshUIDocLineInternal -Lines $lines
    }

    Add-PoshUIDocLineInternal -Lines $lines -Text '### Syntax'
    Add-PoshUIDocLineInternal -Lines $lines
    Add-PoshUIDocLineInternal -Lines $lines -Text '```powershell'
    foreach ($parameterSet in $command.ParameterSets) {
        Add-PoshUIDocLineInternal -Lines $lines -Text (('{0} {1}' -f $CommandName, $parameterSet.ToString()).Trim())
    }
    Add-PoshUIDocLineInternal -Lines $lines -Text '```'
    Add-PoshUIDocLineInternal -Lines $lines

    $description = Get-PoshUIDocHelpTextInternal (
        Get-PoshUIDocPropertyInternal -InputObject $help -Name description
    )
    if ($description) {
        Add-PoshUIDocLineInternal -Lines $lines -Text '### Description'
        Add-PoshUIDocLineInternal -Lines $lines
        Add-PoshUIDocLineInternal -Lines $lines -Text $description
        Add-PoshUIDocLineInternal -Lines $lines
    }

    if ($parameters.Count -gt 0) {
        Add-PoshUIDocLineInternal -Lines $lines -Text '### Parameters'
        Add-PoshUIDocLineInternal -Lines $lines
        Add-PoshUIDocLineInternal -Lines $lines -Text '| Name | Type | Required | Position | Pipeline | Default | Description |'
        Add-PoshUIDocLineInternal -Lines $lines -Text '| --- | --- | --- | --- | --- | --- | --- |'
        foreach ($parameter in $parameters) {
            $name = Get-PoshUIDocPropertyInternal -InputObject $parameter -Name name
            $type = Get-PoshUIDocPropertyInternal -InputObject (
                Get-PoshUIDocPropertyInternal -InputObject $parameter -Name type
            ) -Name name
            if (-not $type) {
                $type = Get-PoshUIDocPropertyInternal -InputObject $parameter -Name parameterValue
            }
            $required = ConvertTo-PoshUIDocBoolInternal (
                Get-PoshUIDocPropertyInternal -InputObject $parameter -Name required
            )
            $position = Get-PoshUIDocPropertyInternal -InputObject $parameter -Name position
            $pipeline = ConvertTo-PoshUIDocBoolInternal (
                Get-PoshUIDocPropertyInternal -InputObject $parameter -Name pipelineInput
            )
            $default = Get-PoshUIDocPropertyInternal -InputObject $parameter -Name defaultValue
            $parameterDescription = Get-PoshUIDocHelpTextInternal (
                Get-PoshUIDocPropertyInternal -InputObject $parameter -Name description
            )
            $cells = @(
                "``-$name``"
                "``$(ConvertTo-PoshUIDocCellInternal $type)``"
                (ConvertTo-PoshUIDocCellInternal $required)
                (ConvertTo-PoshUIDocCellInternal $position)
                (ConvertTo-PoshUIDocCellInternal $pipeline)
                (ConvertTo-PoshUIDocCellInternal $default)
                (ConvertTo-PoshUIDocCellInternal $parameterDescription)
            )
            Add-PoshUIDocLineInternal -Lines $lines -Text ('| {0} |' -f ($cells -join ' | '))
        }
        Add-PoshUIDocLineInternal -Lines $lines
    }

    foreach ($section in @(
            @{ Name = 'Inputs'; Values = $inputs },
            @{ Name = 'Outputs'; Values = $outputs }
        )) {
        $values = [System.Collections.Generic.List[string]]::new()
        foreach ($entry in $section.Values) {
            $value = Get-PoshUIDocHelpTextInternal (
                Get-PoshUIDocPropertyInternal -InputObject (
                    Get-PoshUIDocPropertyInternal -InputObject $entry -Name type
                ) -Name name
            )
            if ($value) { $values.Add($value) }
        }
        if ($values.Count -gt 0) {
            Add-PoshUIDocLineInternal -Lines $lines -Text ("### {0}" -f $section.Name)
            Add-PoshUIDocLineInternal -Lines $lines
            foreach ($value in $values) { Add-PoshUIDocLineInternal -Lines $lines -Text "- $value" }
            Add-PoshUIDocLineInternal -Lines $lines
        }
    }

    if ($examples.Count -gt 0) {
        Add-PoshUIDocLineInternal -Lines $lines -Text '### Examples'
        Add-PoshUIDocLineInternal -Lines $lines
        $index = 1
        foreach ($example in $examples) {
            $code = ([string](Get-PoshUIDocPropertyInternal -InputObject $example -Name code)).Trim()
            $remarks = Get-PoshUIDocHelpTextInternal (
                Get-PoshUIDocPropertyInternal -InputObject $example -Name remarks
            )
            Add-PoshUIDocLineInternal -Lines $lines -Text "#### Example $index"
            Add-PoshUIDocLineInternal -Lines $lines
            if ($code) {
                Add-PoshUIDocLineInternal -Lines $lines -Text '```powershell'
                Add-PoshUIDocLineInternal -Lines $lines -Text $code
                Add-PoshUIDocLineInternal -Lines $lines -Text '```'
                Add-PoshUIDocLineInternal -Lines $lines
            }
            if ($remarks) {
                Add-PoshUIDocLineInternal -Lines $lines -Text $remarks
                Add-PoshUIDocLineInternal -Lines $lines
            }
            $index++
        }
    }

    $notesText = Get-PoshUIDocHelpTextInternal $notes
    if ($notesText) {
        Add-PoshUIDocLineInternal -Lines $lines -Text '### Notes'
        Add-PoshUIDocLineInternal -Lines $lines
        Add-PoshUIDocLineInternal -Lines $lines -Text $notesText
        Add-PoshUIDocLineInternal -Lines $lines
    }

    $lines.ToArray()
}

function Write-PoshUIReferenceInternal {
    param([Parameter(Mandatory)][string]$Destination)

    if (Test-Path -LiteralPath $Destination) {
        Remove-Item -LiteralPath $Destination -Recurse -Force
    }
    [void](New-Item -ItemType Directory -Path $Destination -Force)

    $index = [System.Collections.Generic.List[string]]::new()
    Add-PoshUIDocLineInternal -Lines $index -Text '# Reference'
    Add-PoshUIDocLineInternal -Lines $index -Text $script:GeneratedNotice
    Add-PoshUIDocLineInternal -Lines $index
    Add-PoshUIDocLineInternal -Lines $index -Text 'Generated command reference for the PoshUI module.'
    Add-PoshUIDocLineInternal -Lines $index
    Add-PoshUIDocLineInternal -Lines $index -Text '- [PowerShell command reference](powershell.md)'
    Add-PoshUIDocLineInternal -Lines $index
    Add-PoshUIDocLineInternal -Lines $index -Text 'Run `pwsh ./build.ps1 -Task docs` to refresh these files.'
    Write-PoshUIDocFileInternal -Path (Join-Path $Destination 'README.md') -Lines $index.ToArray()

    $reference = [System.Collections.Generic.List[string]]::new()
    Add-PoshUIDocLineInternal -Lines $reference -Text '# PowerShell reference'
    Add-PoshUIDocLineInternal -Lines $reference -Text $script:GeneratedNotice
    Add-PoshUIDocLineInternal -Lines $reference
    Add-PoshUIDocLineInternal -Lines $reference -Text (
        'Generated from the explicit PoshUI {0} manifest inventory and comment-based help.' -f $script:Manifest.ModuleVersion
    )
    Add-PoshUIDocLineInternal -Lines $reference
    Add-PoshUIDocLineInternal -Lines $reference -Text ("Supported commands: {0}" -f $script:Commands.Count)
    Add-PoshUIDocLineInternal -Lines $reference
    Add-PoshUIDocLineInternal -Lines $reference -Text '| Command | Synopsis |'
    Add-PoshUIDocLineInternal -Lines $reference -Text '| --- | --- |'

    foreach ($commandName in $script:Commands) {
        $command = $script:Module.ExportedCommands[$commandName]
        if ($null -eq $command) {
            throw "Manifest command was not exported by the imported module: $commandName"
        }
        $help = Get-Help -Name $command -Full
        $synopsis = ConvertTo-PoshUIDocCellInternal (
            Get-PoshUIDocPropertyInternal -InputObject $help -Name Synopsis
        )
        Add-PoshUIDocLineInternal -Lines $reference -Text (
            '| [{0}](#{1}) | {2} |' -f $commandName, $commandName.ToLowerInvariant(), $synopsis
        )
    }
    Add-PoshUIDocLineInternal -Lines $reference

    foreach ($commandName in $script:Commands) {
        foreach ($line in (Get-PoshUICommandReferenceInternal -CommandName $commandName)) {
            Add-PoshUIDocLineInternal -Lines $reference -Text $line
        }
    }
    Write-PoshUIDocFileInternal -Path (Join-Path $Destination 'powershell.md') -Lines $reference.ToArray()
}

function Get-PoshUIDocFileMapInternal {
    param([Parameter(Mandatory)][string]$Path)

    $map = @{}
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return $map }
    $root = (Resolve-Path -LiteralPath $Path).Path
    foreach ($file in (Get-ChildItem -LiteralPath $root -Recurse -File | Sort-Object FullName)) {
        $relative = [IO.Path]::GetRelativePath($root, $file.FullName) -replace '\\', '/'
        $map[$relative] = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash
    }
    $map
}

function Compare-PoshUIDocReferenceInternal {
    param(
        [Parameter(Mandatory)][string]$Expected,
        [Parameter(Mandatory)][string]$Actual
    )

    $expectedMap = Get-PoshUIDocFileMapInternal $Expected
    $actualMap = Get-PoshUIDocFileMapInternal $Actual
    $differences = [System.Collections.Generic.List[string]]::new()
    foreach ($path in @($expectedMap.Keys + $actualMap.Keys | Sort-Object -Unique)) {
        if (-not $expectedMap.ContainsKey($path)) { $differences.Add("extra generated file: $path"); continue }
        if (-not $actualMap.ContainsKey($path)) { $differences.Add("missing generated file: $path"); continue }
        if ($expectedMap[$path] -ne $actualMap[$path]) { $differences.Add("changed generated file: $path") }
    }
    if ($differences.Count -gt 0) {
        throw "Generated docs are stale: $($differences -join '; '). Run: pwsh ./build.ps1 -Task docs"
    }
    Write-Host 'Generated docs are current.'
}

$previousMode = $env:POSH_UI_MODE
try {
    $env:POSH_UI_MODE = 'off'
    $script:Module = Import-Module -Name $script:ResolvedManifest -Force -PassThru -ErrorAction Stop

    if ($Check) {
        $temporaryParent = Join-Path ([Environment]::GetFolderPath('UserProfile')) 'tmp'
        [void](New-Item -ItemType Directory -Path $temporaryParent -Force)
        $temporaryRoot = Join-Path $temporaryParent ("posh-ui-docs-{0}" -f [guid]::NewGuid().ToString('N'))
        try {
            Write-PoshUIReferenceInternal -Destination $temporaryRoot
            Compare-PoshUIDocReferenceInternal -Expected $OutputRoot -Actual $temporaryRoot
        }
        finally {
            if (Test-Path -LiteralPath $temporaryRoot) {
                Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
            }
        }
    }
    elseif ($PSCmdlet.ShouldProcess($OutputRoot, 'Generate PoshUI reference documentation')) {
        Write-PoshUIReferenceInternal -Destination $OutputRoot
        Write-Host 'Generated docs written to docs/reference.'
    }
}
finally {
    if ($null -ne $script:Module) {
        Remove-Module -ModuleInfo $script:Module -Force -ErrorAction SilentlyContinue
    }
    if ($null -eq $previousMode) { Remove-Item Env:\POSH_UI_MODE -ErrorAction SilentlyContinue }
    else { $env:POSH_UI_MODE = $previousMode }
}
